### ISSUE TITLE
Wind offshore capacity factor rule fails

### ISSUE THREAD

**Issue by adrienmellot** [calliope-project/euro-calliope#328]
### What happened?

The wind offshore capacity factor rule fails, at all spatial resolutions.

### Version

1.2.0.dev

### Relevant log output

```shell
snakemake --profile profiles/conda --configfile="config/default.yaml" "build/models/national/timeseries/supply/capacityfactors-wind-offshore.csv"
Config file config/default.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job stats:
job                          count    min threads    max threads
-------------------------  -------  -------------  -------------
capacity_factors_offshore        1              1              1
total                            1              1              1

Select jobs to execute...

[Tue Apr  9 11:54:22 2024]
Job 0: Generate capacityfactor time series disaggregated by location on national resolution for wind-offshore.
Reason: Missing output files: build/models/national/timeseries/supply/capacityfactors-wind-offshore.csv

Activating conda environment: ../envs/snakemake/euro-calliope/9498f8bccfbf440ed1c00845fc76b38a_
Activating conda environment: ../envs/snakemake/euro-calliope/9498f8bccfbf440ed1c00845fc76b38a_
/Users/adrienmellot/Documents/GitHub/envs/snakemake/euro-calliope/9498f8bccfbf440ed1c00845fc76b38a_/lib/python3.9/site-packages/geopandas/array.py:275: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  return GeometryArray(vectorized.points_from_xy(x, y, z), crs=crs)
Traceback (most recent call last):
  File "/Users/adrienmellot/Documents/GitHub/euro-calliope/.snakemake/scripts/tmpwp_m_t5h.capacityfactors_offshore.py", line 84, in <module>
    capacityfactors(
  File "/Users/adrienmellot/Documents/GitHub/euro-calliope/.snakemake/scripts/tmpwp_m_t5h.capacityfactors_offshore.py", line 55, in capacityfactors
    capacityfactors_per_eez = area_weighted_time_series(
  File "/Users/adrienmellot/Documents/GitHub/euro-calliope/lib/eurocalliopelib/geo/spatiotemporal.py", line 33, in area_weighted_time_series
    data={
  File "/Users/adrienmellot/Documents/GitHub/euro-calliope/lib/eurocalliopelib/geo/spatiotemporal.py", line 34, in <dictcomp>
    shape_id: weighted_time_series(
  File "/Users/adrienmellot/Documents/GitHub/euro-calliope/lib/eurocalliopelib/geo/spatiotemporal.py", line 84, in weighted_time_series
    assert ds.weight.sum() >= gridcell_overlap_threshold, ds.weight.sum()
AssertionError: <xarray.DataArray 'weight' ()>
array(0.58280955)
Coordinates:
    shape_id  int64 64459
[Tue Apr  9 11:55:28 2024]
Error in rule capacity_factors_offshore:
    jobid: 0
    input: build/data/eez.geojson, build/data/national/shared-coast.csv, data/automatic/capacityfactors/wind-offshore-timeseries.nc
    output: build/models/national/timeseries/supply/capacityfactors-wind-offshore.csv
    conda-env: /Users/adrienmellot/Documents/GitHub/envs/snakemake/euro-calliope/9498f8bccfbf440ed1c00845fc76b38a_

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-04-09T115421.386948.snakemake.log
```

**Comment by brynpickering** [comment]
It is caused by this EEZ region: https://marineregions.org/gazetteer.php?p=details&id=64459

I assume it's a region introduced in a newer EEZ dataset that is being downloaded and it is partially outside the geographic range of the capacity factor data.

Confirmed that EEZ v11 does _not_ have this MRGID. So it's a version change. The current source doesn't allow versioned EEZ access, so we should upload EEZ v11 to Zenodo (it's CCBY4 licensed)

**Comment by brynpickering** [comment]
@calliope-project/euro-calliope-devs please delete `data/automatic/eez.zip`, pull in latest changes on `develop`, then run snakemake to build `data/automatic/eez.gpkg.zip`.
