### ISSUE TITLE
e-highways connection problems in full workflow

### ISSUE THREAD

**Issue by adrienmellot** [calliope-project/euro-calliope#397]
### What happened?

Running the full workflow, the ehighways resolution failed in rule `link_locations_with_transmission_techs_template`. 
See log below.

### Version

1.2.0.dev

### Relevant log output

```shell
[Tue Jun 11 12:44:46 2024]
Job 406: Link ehighways direct neighbours and neighbours with sea connections with transmission techs from template.
Reason: Missing output files: build/models/ehighways/techs/transmission/electricity-linked-neighbours.yaml; Updated input files: build/data/ehighways/units.geojson

Activating conda environment: ../envs/snakemake/euro-calliope/afba709282c28f1f96f3b898cb927b2e_
Activating conda environment: ../envs/snakemake/euro-calliope/afba709282c28f1f96f3b898cb927b2e_
Traceback (most recent call last):
  File "/Users/adrienmellot/Documents/GitHub/euro-calliope/.snakemake/scripts/tmp0axpx5qw.template_transmission.py", line 70, in <module>
    construct_techs_and_links(
  File "/Users/adrienmellot/Documents/GitHub/euro-calliope/.snakemake/scripts/tmp0axpx5qw.template_transmission.py", line 27, in construct_techs_and_links
    assert nx.is_connected(graph), "There are electrical islands in the network graph."
AssertionError: There are electrical islands in the network graph.
RuleException:
CalledProcessError in file /Users/adrienmellot/Documents/GitHub/euro-calliope/./rules/transmission.smk, line 52:
Command 'source /Users/adrienmellot/miniconda3/bin/activate '/Users/adrienmellot/Documents/GitHub/envs/snakemake/euro-calliope/afba709282c28f1f96f3b898cb927b2e_'; set -euo pipefail;  python /Users/adrienmellot/Documents/GitHub/euro-calliope/.snakemake/scripts/tmp0axpx5qw.template_transmission.py' returned non-zero exit status 1.
[Tue Jun 11 12:44:48 2024]
Error in rule link_locations_with_transmission_techs_template:
    jobid: 406
    input: templates/models/techs/transmission/electricity-transmission.yaml, build/data/ehighways/units.geojson
    output: build/models/ehighways/techs/transmission/electricity-linked-neighbours.yaml
    conda-env: /Users/adrienmellot/Documents/GitHub/envs/snakemake/euro-calliope/afba709282c28f1f96f3b898cb927b2e_

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-06-11T124347.887384.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```

**Comment by brynpickering** [comment]
Yep, I also found it and am working on it!
