### ISSUE TITLE
Script output is not added to log files

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#94]
Snakemake creates log files of each run. These log files can be useful for debugging.

Whatever output our scripts create is _not_ added to these logs at this point -- not even Tracebacks. We should make sure all output ends in log files; either the main Snakemake log files or separate log files that we create per rule.

Example:

This is console output of a local I made fail. The parts that I marked with `#` are not within the log file.
```
[Wed Apr 28 16:39:28 2021]
Job 1: Determine performance indicators of all runs.

Activating conda environment: /Users/trtim/Develop/balancing-act/.snakemake/conda/ca303607d6808744ca7fe7318e4d9f7d
# Traceback (most recent call last):
#  File "/Users/trtim/Develop/balancing-act/.snakemake/scripts/tmpqkqirqfr.performance.py", line 52, in <module>
#    performance_indicators(
#  File "/Users/trtim/Develop/balancing-act/.snakemake/scripts/tmpqkqirqfr.performance.py", line 11, in performance_indicators
#    agg = agg2
# NameError: name 'agg2' is not defined**
[Wed Apr 28 16:39:32 2021]
Error in rule performance_indicators:
    jobid: 1
    output: build/output/continental/performance.nc
    conda-env: /Users/trtim/Develop/balancing-act/.snakemake/conda/ca303607d6808744ca7fe7318e4d9f7d

RuleException:
CalledProcessError in line 78 of /Users/trtim/Develop/balancing-act/rules/analyse.smk:
Command 'source /Users/trtim/miniconda3/bin/activate '/Users/trtim/Develop/balancing-act/.snakemake/conda/ca303607d6808744ca7fe7318e4d9f7d'; set -euo pipefail;  python /Users/trtim/Develop/balancing-act/.snakemake/scripts/tmpqkqirqfr.performance.py' returned non-zero exit status 1.
  File "/Users/trtim/miniconda3/envs/balancing-act/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2326, in run_wrapper
  File "/Users/trtim/Develop/balancing-act/rules/analyse.smk", line 78, in __rule_performance_indicators
  File "/Users/trtim/miniconda3/envs/balancing-act/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/Users/trtim/miniconda3/envs/balancing-act/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/Users/trtim/miniconda3/envs/balancing-act/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/Users/trtim/miniconda3/envs/balancing-act/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/trtim/Develop/balancing-act/.snakemake/log/2021-04-28T163926.077480.snakemake.log
```

**Comment by timtroendle** [comment]
The Snakemake linter (`snakemake --lint`) is complaining about the same. It expects a `log` directive for each rule.

**Comment by timtroendle** [comment]
For some details on implementation, see #367.
